module.exports = {
"SimpleStorage": require('./SimpleStorage.js').default,
"TokTst": require('./TokTst.js').default,
"ExpertPrices": require('./ExpertPrices.js').default,
"ExpertsRewards": require('./ExpertsRewards.js').default,
"Context": require('./Context.js').default,
"Roles": require('./Roles.js').default,
"MinterRole": require('./MinterRole.js').default,
"SafeMath": require('./SafeMath.js').default,
"ERC20": require('./ERC20.js').default,
"ERC20Capped": require('./ERC20Capped.js').default,
"ERC20Detailed": require('./ERC20Detailed.js').default,
"ERC20Mintable": require('./ERC20Mintable.js').default,
"IERC20": require('./IERC20.js').default,
"Experts": require('./Experts.js').default,
"Exchange": require('./Exchange.js').default,
"OraclePrice": require('./OraclePrice.js').default,
"Faucet": require('./Faucet.js').default,
"DAItest": require('./DAItest.js').default,
"ALFtst": require('./ALFtst.js').default,
"QUBtst": require('./QUBtst.js').default,
"ANGtst": require('./ANGtst.js').default,
};